### PR TITLE
[Bug / game.html / list items] #59

### PR DESCRIPTION
**Pull request by PaulaR-05**
Hey Guys, I fixed a bug that was on the list item. Could you review it, please? Thanks!

### CODE REVIEW

**Review by Emimint — APPROVED** [review]
Good for me 👍 !

**Comment by mnichols08** [comment]
I close it to recreate the branch name as 60-bug-list-PaulaR-05.

**Review by mnichols08 — APPROVED** [review]
I approve again.

The naming convention is confusing. This is #60 but solves #59

**Comment by mnichols08** [comment]
Makes sense when I see it in action but it didn't at first.

**Pull request merged**
