### PR TITLE
merges development changes during Sprint III with main branch

### PR DESCRIPTION
**Pull request by mnichols08**
closes issue #91

### CODE REVIEW

**Review by Emimint — APPROVED** [review]
All good for me!

**Review by PaulaR-05 — APPROVED** [review]

**Comment by mnichols08** [comment]
closes issue #91

**Comment by mnichols08** [comment]
@Nazile-Tag or @emilio12345 We need a review from one of you to push this change to the main branch =)

**Review by Nazile-Tag — APPROVED** [review]
everything seems OK

**Pull request merged**
